package inventivelink.com.fb2sql.ymentities

class YMNodeNames {
    companion object {
    const val MUMS_NODE = "mums"
    const val YOOMUM_ACCOUNT_NODE = "yooMumAccount"
    const val CONVERSATIONS_NODE = "conversations"
    const val MESSAGES_NODE = "messages"
    const val FEED_NODE = "feed"
    const val LIKES_NODE = "likes"
    const val CHILDREN_NODE = "children"
    const val FRIENDS_NODE = "friends"
    const val FRIENDS_RECEIVED_NODE = "received"
    const val FRIENDS_ACCEPTED_NOTIFICATION_NODE = "accepted-notifications"
    const val INTERESTS_NODE = "interests"
    const val EVENTS_EVENTS_INVITED_NODE = "eventsInvited"
    const val PROFILE_PICS_FOLDER = "usersProfilePics/"
    const val LOCATIONS_GEOHASH_NODE = "locations-locations"
    const val EVENTS_PICS_FOLDER = "eventsPics/"
    const val LOCATIONS_PICS_FOLDER = "locationPics/"
    const val MUMS_LOCATION_NODE = "mums-locations/"
    const val EVENT_COMMENTS_NODE = "event-comments"
    const val LOCATION_COMMENTS_NODE = "location-comments"
    const val COMMENTS_NODE = "comments"
    const val COMMENT_NODE = "comment"
    const val MESSAGE_NODE = "message"
    const val EVENTS_NODE = "events"
    const val EVENT_PARTICIPANTS = "participants"
    const val EVENT_GEOHASH_NODE = "geoHash"
    const val START_DATE_FIELD = "startDate"
    const val TIMESTAMP_FIELD = "timestamp"
    const val TIMESTAMP_END_FIELD = "timestampEnd"
    const val DELETED_FIELD = "deleted"
    const val LOCATIONS_NODE = "locations"
    const val FAVORITE_LOCATIONS_NODE = "favoriteLocations"
    const val LOCATION_CATEGORY_CHILDBIRTH_NODE = "preparation"
    const val LOCATION_CATEGORY_HEALTH_NODE = "health"
    const val LOCATION_CATEGORY_CRECHE_NODE = "nurseries"
    const val LOCATION_CATEGORY_CLOTH_NODE = "clothing_equipment"
    const val LOCATION_CATEGORY_COFFEE_NODE = "activities"
    const val LOCATION_CATEGORY_WELLBEING_NODE = "beauty_wellness"
    const val LOCATION_REMOVE_NODE = "deactivated"
    const val LOCATION_TYPE_CHILD = "type"
    const val LOCATION_DESCRIPTION_CHILD = "description"
    const val LAST_CONNECTION_TIMESTAMP = "lastConnectionTimestamp"
    const val PLACE_ID_CHILD = "placeID"
    const val GETTING_EVENT_STEP_COUNT = 50
    const val NUMBER_OF_MESSAGES_PER_PAGE = 25
    }
}